# Generated by Django 5.1 on 2024-10-24 19:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('numero_registro', models.FloatField()),
                ('edad', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('descripcion', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
