# Generated by Django 5.1 on 2024-10-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ganado', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reses',
            old_name='nombre',
            new_name='raza',
        ),
        migrations.RemoveField(
            model_name='reses',
            name='image',
        ),
    ]
