# Generated by Django 5.1.3 on 2024-11-16 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_ganado', '0004_reses_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reses',
            name='peso',
            field=models.FloatField(),
        ),
    ]
